name: CI-CD
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch app to pull'
        required: true
        default: 'main'
  push:
    branches:
      - main
        
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    env:
      NODEJS_APP_PATH: ${{ vars.NODEJS_APP_PATH }}
      NODEJS_APP_NAME: ${{ vars.NODEJS_APP_NAME }}
    steps:
      - name: Clean up workspace
        run: |
          echo "Cleaning up temporary files..."
          rm -rf $(pwd)/*
          
      - name: Checkout ${{ vars.USERNAME }}/poc-nodejs repository
        uses: actions/checkout@v2
        with:
          repository: ${{ vars.USERNAME }}/poc-nodejs
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ref: ${{ inputs.branch }}
          path: ${{ vars.NODEJS_APP_NAME }}

      - name: Create dir
        run: |
          if [ ! -d $NODEJS_APP_PATH ]; then
              mkdir -p $NODEJS_APP_PATH
              echo "Directory created: $NODEJS_APP_PATH"
          fi
          
      - name: Copy files to target dir
        run: |
          if [ -d $NODEJS_APP_PATH ]; then
              cp * $NODEJS_APP_PATH
              echo "Files copied to: $NODEJS_APP_PATH"
          else
              echo "Dir not found!! : $NODEJS_APP_PATH"
          fi
          
      - name: Install package with npm
        run: |
          cd $NODEJS_APP_PATH
          npm install
        

