name: CI-CD
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch app to pull'
        required: true
        default: 'main'
  push:
    branches:
      - main
        
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    steps:
      - name: Clean up workspace
        run: |
          echo "Cleaning up temporary files..."
          rm -rf $(pwd)/*
          rm -rf ${{ vars.NODEJS_APP_PATH }}/*
          
      - name: Checkout ${{ vars.USERNAME }}/poc-nodejs repository
        uses: actions/checkout@v2
        with:
          repository: ${{ vars.USERNAME }}/poc-nodejs
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ref: ${{ inputs.branch }}
          path: ${{ vars.NODEJS_APP_NAME }}
          fetch-depth: 1
          submodules: false

      - name: Create dir
        run: |
          if [ ! -d "${{ vars.NODEJS_APP_PATH }}" ]; then
              mkdir -p ${{ vars.NODEJS_APP_PATH }}
              echo "Directory created: ${{ vars.NODEJS_APP_PATH }}"
          fi
        
      - name: Copy files to target dir
        run: |
          if [ -d "${{ vars.NODEJS_APP_PATH }}" ]; then
              cp -r $(pwd)/${{ vars.NODEJS_APP_NAME }}/* ${{ vars.NODEJS_APP_PATH }}/
              echo "Files copied to: ${{ vars.NODEJS_APP_PATH }}"
          else
              echo "Dir not found!! : ${{ vars.NODEJS_APP_PATH }}"
          fi
          
      - name: Install package with npm
        run: |
          npm install
        
      - name: Start app!
        run: |
          pm2 start index.js --name '${{ vars.NODEJS_APP_NAME }}'
          sleep 2
          curl http://localhost:3000/test
