name: CI-CD
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to pull'
        required: true
        default: 'main'
        
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-dev

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
    
      - name: Download poc-nodejs as ZIP
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          BRANCH: ${{ inputs.branch }}
        run: |
          curl -H "Authorization: token $GITHUB_TOKEN" \
               -L -o poc-nodejs.zip \
               https://api.github.com/repos/chaiyodcymg/poc-nodejs/poc-nodejs/$BRANCH
               unzip poc-nodejs.zip -d poc-nodejs
               ls poc-nodejs

               
      - name: Run my variable
        run: echo "my variable :${{ vars.USER_NAME }}"
