name: CI-CD
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to pull'
        required: true
        default: 'main'
        
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    steps:
      - name: Clean up workspace
        run: |
          echo "Cleaning up temporary files..."
          rm -rf $(pwd)/*
          
      - name: Checkout another repository
        uses: actions/checkout@v2
        with:
          repository: ${{ vars.USERNAME }}/poc-nodejs  
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ inputs.branch }}
          
      - name: Download poc-nodejs as ZIP
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          BRANCH: ${{ inputs.branch }}
        run: |
          # curl -H "Authorization: token $GITHUB_TOKEN" \
          #      -L -o poc-nodejs.zip \
          #      https://github.com//${{ vars.USER_NAME }}/poc-nodejs/archive/refs/heads/$BRANCH.zip
          # pwd
          # echo "====================================================="
          ls -l

